{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "liberty-feature-repo-19004",
    "namespace": "default",
    "labels": {
      "app": "liberty-feature-repo-19004"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "http",
        "protocol": "TCP",
        "port": 9080,
        "targetPort": 9080
      }
    ],
    "selector": {
      "app": "liberty-feature-repo-19004"
    },
    "type": "NodePort"
  }
}
